### ISSUE TITLE
GetFinisherFromDescriptors appears missing

### ISSUE THREAD

**Issue by stefanpenner** [tc39/proposal-decorators-previous#11]

**Comment by bterlson** [comment]
This is not present in the latest spec text?

**Comment by stefanpenner** [comment]
@bterlson it resides here: https://github.com/tc39/proposal-decorators/commit/c32ea181569668a6c1ef212c1a85071e2bf53466#diff-f1495ac117d520f227135771ad2006eaR535

**Comment by bterlson** [comment]
The latest is in the diffspec branch.

**Comment by stefanpenner** [comment]
Ah, https://github.com/tc39/proposal-decorators/commits/diffspec is where work is happening? /facepalm.

Is there a reason why the active work, isn't on the main branch?

**Comment by bterlson** [comment]
See also https://tc39.github.io/proposal-decorators

**Comment by bterlson** [comment]
it hasn't been merged yet is all. I could merge it I guess.

**Comment by stefanpenner** [comment]
@bterlson ya, didn't realize active dev was off main-branch. A PR could have made this more obvious. Next time I'll ping and ask.
