### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by smelukov** [tc39/proposal-decorators-previous#39]
Hi! Is there any chance that this proposal will grow up to stage 3/4?

**Comment by bathos** [comment]
The decorators proposal is in flight, but it’s complex and has implications for many others, so there’s a lot to review, I think. According to the [TC39 agendas repo](https://github.com/tc39/agendas/blob/master/2017/09.md) it looks like the next meeting does not seek to advance the stage, but there is an hour being allocated to continuing discussion of semantics:

> 1. Timeboxed agenda items
>     [...]
>     1. 60 Minute Items
>         1. [Private methods and accessors](https://github.com/littledan/proposal-private-methods) for Stage 3 (Daniel Ehrenberg)
>         1. [Decorators](https://github.com/littledan/proposal-unified-class-features): detailed discussion of proposed semantics (Daniel Ehrenberg)

**Comment by smelukov** [comment]
@bathos thanks

**Comment by pelotom** [comment]
Is there an account anywhere of whether and how things progressed during this meeting? Are we anywhere closer to decorators graduating to stage 3? The TypeScript community is holding its breath...

**Comment by bathos** [comment]
@pelotom I haven’t read the September notes yet myself, but I think what you want is at [tc39-notes](https://github.com/rwaldron/tc39-notes/tree/master/es8/2017-09).

---

Edit: more specifically [12.iv.b](https://github.com/rwaldron/tc39-notes/blob/master/es8/2017-09/sep-27.md#12ivb-decorators-detailed-discussion-of-proposed-semantics) and [12.iv.b continued](https://github.com/rwaldron/tc39-notes/blob/master/es8/2017-09/sep-28.md#12ivb-decorators-detailed-discussion-of-proposed-semantics-cont), though there appear to be some other items where interactions with decorators are also discussed in passing.

**Comment by littledan** [comment]
I put them on the agenda for the next meeting. I was thinking to propose it for advancement to Stage 3 in November or January.

**Comment by pelotom** [comment]
@littledan that's great news, thanks for the update!
